services:
  - type: web
    name: pop
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/population
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
